on:
  workflow_dispatch:
    inputs:
      Submodule-Name:
        description: name of the directory to migrate as submodule
        required: true
        type: string

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Filter the directory from inputs
        run: |
          git filter-branch --subdirectory-filter ${{ github.event.inputs.Submodule-Name }} -- --all
          echo "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: Import GPG key
        run: |
          keybase pgp export -q ${{ secrets.GPG_PUBLIC_KEY }} | gpg --import
          keybase pgp export -q ${{ secrets.GPG_PUBLIC_KEY }} --secret | gpg --allow-secret-key-import --import

      - name: Get all the commits signed
        run: |
          gpg --list-secret-keys --keyid-format=long 
