on:
  push:
    
jobs:
  testing:
    name: Testing-workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Install Verdaccio
        run: npm install verdaccio -g

      - name: Install pm2
        run: npm install pm2 -g

      - name: Replace verdaccio config file
        run: |
          mkdir ~/.config/verdaccio
          cp config.yaml ~/.config/verdaccio/config.yaml
          echo $HOME

      - name: Cache Verdaccio Data
        id: cache-verdaccio
        uses: actions/cache@v3
        env:
          cache-name: cache-verdaccio-data
        with:
          path: ~/.config/verdaccio/storage
          key: cache-npm-${{ hashFiles('./package-lock.json')}}
          restore-keys: cache-npm-

      - name: Start running Verdaccio in background
        continue-on-error: true
        run: pm2 start --name VERDACCIO verdaccio

      - name: Install dependencies
        run: npm ci --registry=http://localhost:4873

      - name: out
        run: |
          cd ~/.config/verdaccio
          ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: verdaccio-logs
          path: /home/runner/verdaccio.log