on:
  workflow_dispatch:
    inputs:
      Submodule-Name:
        description: name of the directory to migrate as submodule
        required: true
        type: string

      Email-Id-For-Git-Config:
        description: email id of the developer running this for git configuration
        type: string
        default: "chiranjeevi.vatsal@oslash.com"

      Name-For-Git-Config:
        description: name of the developer running this for git configuration
        type: string
        default: Chiranjeevi

      Name-Of-Directory:
        description: name of the directory that needs to be pushed as submodule
        type: string
        required: true

      Name-Of-Submodule:
        description: name of the submodule to be created
        type: string
        required: true

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Filter the directory from inputs
        run: |
          git remote rm origin
          git filter-branch --subdirectory-filter ${{ github.event.inputs.Submodule-Name }} -- --all

      - name: Setup GPG keys for verification
        run: |
          echo "$GPG_PUBLIC_KEY" > public.key
          gpg --import public.key
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --import private.key
          gpg --list-secret-keys --keyid-format=long
          
      - name: Create the repo for submodule
        run: |
          gh repo create ${{ github.event.inputs.Name-Of-Submodule }} --private

      - name: Get all the commits signed
        run: |
          git config --global user.email ${{ github.event.inputs.Email-Id-For-Git-Config }}
          git config --global user.name ${{ github.event.inputs.Name-For-Git-Config }}
          git config --global user.signingkey $KEY_ID
          git remote add origin https://vchiranjeeviako:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/vchiranjeeviako/${{ github.event.inputs.Submodule-Name }}
          GIT_EDITOR=true git rebase --exec 'git commit --amend --no-edit -n -S' -i --root
          git push --set-upstream origin main
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}
