on:
  push:
    
jobs:
  testing:
    name: Testing-workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      # - name: Install Verdaccio
      #   run: npm install verdaccio -g

      # - name: Install pm2
      #   run: npm install pm2 -g

      # - name: Replace verdaccio config file
      #   run: |
      #     mkdir ~/.config/verdaccio
      #     cp config.yaml ~/.config/verdaccio/config.yaml
      #     echo $HOME

      - name: Cache node_modules
        id: cache-nm
        uses: actions/cache@v3
        env:
          cache-name: cache-nm
        with:
          path: node_modules
          key: cache-npm-${{hashFiles('./package.json')}}-${{ hashFiles('./package-lock.json')}}
          # restore-keys: cache-npm-

      - name: Install dependencies
        if: ${{ steps.cache-nm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm ci

      # - name: out
      #   run: |
      #     cd ~/.config/verdaccio
      #     ls -la

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: verdaccio-logs
      #     path: /home/runner/verdaccio.log