on:
  push:
    branches:
      - main
    
jobs:
  testing:
    name: Testing-workflow
    if: ${{ contains(github.event.head_commit.message, '[mesh]') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build command
        run: turbo build
