on:
  push:
    branches:
      - main
    
jobs:
  testing:
    name: Testing-workflow
    if: ${{ contains(github.event.head_commit.message, '[mesh]') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Install node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build command
        run: turbo run test --filter=[HEAD^1]
