on:
  push:
    branches:
      - main
    
jobs:
  testing:
    name: Testing-workflow
    if: ${{ contains(github.event.head_commit.message, '[mesh]') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Install node ⚙️
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build command
        run: npm run lint

      - name: Get out
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: out
        run: echo "$set-output"
