on:
  push:
    
jobs:
  testing:
    name: Testing-workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Something
        if: always() && steps.0.outcome == 'failure'
        run: |
          echo "came here"
        
      - name: Something else
        run: echo "should come"