on:
  push:
    
jobs:
  testing:
    name: Testing-workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        id: checkout-repo
        uses: actions/checkout@v3

      - name: Upload sst-apis stack outputs
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: sst-apis-stacks
          path: backend/sst-api/

      - name: Something
        run: |
          echo "came here"
        
      - name: Something else
        run: echo "should come"