on:
  workflow_dispatch:
    inputs:
      Submodule-Name:
        description: name of the directory to migrate as submodule
        required: true
        type: string

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3

      - name: Filter the directory from inputs
        run: |
          git filter-branch --subdirectory-filter ${{ github.event.inputs.Submodule-Name }} -- --all
          echo "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true 

      - name: Get all the commits signed
        run: |
          GIT_EDITOR=true git rebase --exec -i --root

      - name: Change the remote origin
        run: |
          git remote rm origin
          git remote add origin https://www.github.com/vchiranjeeviako/${{ github.event.inputs.Submodule-Name }}
          git push
