on:
  workflow_dispatch:
    # inputs:
    #   Submodule-Name:
    #     description: name of the directory to migrate as submodule
    #     required: true
    #     type: string

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3

      - name: Filter the directory from inputs
        run: |
          echo "Private key"
          echo "${{ secrets.GPG_PRIVATE_KEY }}"
          echo "Passphrase"
          echo "${{ secrets.PASSPHRASE }}"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Get all the commits signed
        run: |
          gpg --list-secret-keys --keyid-format=long 
