on:
  workflow_dispatch:
    inputs:
      Submodule-Name:
        description: name of the directory to migrate as submodule
        required: true
        type: string

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Filter the directory from inputs
        run: |
          git filter-branch --subdirectory-filter ${{ github.event.inputs.Submodule-Name }} -- --all
          

      - name: Get all the commits signed
        run: |
          echo "$GPG_PUBLIC_KEY" > public.key
          gpg --import public.key
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --import private.key
          gpg --list-secret-keys --keyid-format=long
          git config --global user.email "chiranjeevi.vatsal@oslash.com"
          git config --global user.name "Chiranjeevi"
          git config --global user.signingkey $KEY_ID
          GIT_EDITOR=true git rebase --exec 'git commit --amend --no-edit -n -S' -i --root
          git remote rm origin
          git remote add origin https://www.github.com/vchiranjeeviako/${{ github.event.inputs.Submodule-Name }}
          git push
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.KEY_ID }}

      - name: Push code
        run: git 
