on:
  push:
    branches:
      - main
    
jobs:
  testing:
    name: Testing-workflow
    if: ${{ contains(github.event.head_commit.message, '[mesh]') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Get out
        env: ${{ secrets.PAT }}
        run: |
          LAST_JOB_STATUS=$(gh run list --workflow test.yml)
          echo "$LAST_JOB_STATUS"

      - name: out
        run: echo "$sha_short"
