on:
  workflow_dispatch:
    inputs:
      Submodule-Name:
        description: name of the directory to migrate as submodule
        required: true
        type: string

jobs:
  Migrate-submodule-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the monorepo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Filter the directory from inputs
        run: |
          git filter-branch --subdirectory-filter ${{ github.event.inputs.Submodule-Name }} -- --all
          echo "${{ secrets.GPG_PRIVATE_KEY }}"

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Get all the commits signed
        run: |
          echo "$GIT_AUTHOR_NAME"
          echo "$GPG_PRIVATE_KEY" > private.key
          gpg --import private.key
          cd ~/.gnupg/private-keys-v1.d
          ls -la
          gpg --list-secret-keys --keyid-format=long
          GIT_EDITOR=true git rebase --exec 'git commit --amend --no-edit -n -S' -i --root
        env:
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
