on:
  push:
    
jobs:
  testing:
    name: Testing-workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Install Verdaccio
        run: npm install verdaccio -g

      - name: Install pm2
        run: npm install pm2 -g

      - name: Replace verdaccio config file
        run: |
          mkdir ~/.config/verdaccio
          cp config.yaml ~/.config/verdaccio/config.yaml

      - name: Cache Verdaccio Data
        id: cache-verdaccio
        uses: actions/cache@v3
        env:
          cache-name: cache-verdaccio-data
        with:
          path: home/runner/.config/verdaccio/storage
          key: cache-npm-${{ hashFiles('./package-lock.json')}}
          restore-keys: cache-npm-

      - name: Start running Verdaccio in background
        continue-on-error: true
        run: |
          pm2 start --name VERDACCIO verdaccio
          cd ../../..
          cd ..
          ls -la
          cd ..
          ls -la

      - name: Install dependencies
        run: npm ci --registry=http://localhost:4873

      - name: After installing
        run: |
          cd ../../..
          cd ..
          ls -la
          cd ..
          ls -la

      - name: Last
        run: echo "Done."
